//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IntelliCAD.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_MAIN                        112
#define IDR_POPUP_EDIT                  119
#define IDR_MENU_SLICE_FILTER           119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_IntelliCADTYPE              130
#define IDR_PASTE_MENU                  151
#define IDR_MENU_VOLUME_RENDERING_FILTER 153
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_MAIN_RIBBON                 307
#define IDD_DIALOG_INSPECTOR            310
#define IDD_DIALOG_LOGIN                312
#define IDB_LOGO_IMG                    320
#define IDD_DIALOG_IMAGE_INFO           326
#define IDB_RIBBON_IMG_PROC_PANEL       328
#define IDD_DIALOG_SLICE_FILTER         329
#define IDD_DIALOG_SERVER_INTERACTION_INACTIVE 330
#define IDD_DIALOG_SERVER_INTERACTION_ACTIVE 331
#define IDD_DIALOG_LOG                  332
#define IDB_RIBBON_IMG_PROC_PANEL_SMALL 332
#define IDD_DIALOG_VOLUME_RENDERING_FILTER 333
#define IDB_RIBBON_VOLUME_RENDERING_PANEL 333
#define IDB_RIBBON_VOLUME_RENDERING_PANEL_SMALL 334
#define IDB_RIBBON_IMG_NETWORK_PANEL    335
#define IDR_MENU1                       337
#define IDB_RIBBON_NETWORK_PANEL        338
#define IDB_RIBBON_FILE                 339
#define IDB_MAIN_LOGO_IMG               341
#define IDB_RIBBON_DIGNOSIS_PANEL       343
#define IDR_ACCELERATOR_SLICE_FILTER_DLG 345
#define IDR_ACCELERATOR_VOLUME_RENDERING_FILTER_DLG 346
#define IDC_STATIC_GBOX_volInfo         1000
#define IDC_STATIC_GBOX_volSize         1001
#define IDC_STATIC_LABEL_volSizeX       1002
#define IDC_STATIC_LABEL_volSizeY       1003
#define IDC_STATIC_LABEL_volSizeZ       1004
#define IDC_STATIC_STEXT_volSizeX       1005
#define IDC_STATIC_STEXT_volSizeY       1006
#define IDC_STATIC_STEXT_volSizeZ       1007
#define IDC_STATIC_LABEL_volPath        1008
#define IDC_STATIC_STEXT_volPath        1009
#define IDC_BUTTON1                     1012
#define IDC_LOGINDLG_BUTTON_SIGN_IN     1012
#define IDC_SERVER_ACTIVE_BUTTON_imgDownTest 1012
#define IDC_LOG_BUTTON_initLog          1012
#define IDC_EDIT3                       1013
#define IDC_EDIT_ID                     1013
#define IDC_LOGINDLG_EDIT_ID            1013
#define IDC_LOG_BUTTON_dump             1013
#define IDC_EDIT4                       1014
#define IDC_LOGINDLG_EDIT_PW            1014
#define IDC_BUTTON3                     1016
#define IDC_EDIT15                      1018
#define IDC_IMG_INFO_EDIT_memSizeW      1018
#define IDC_BUTTON2                     1019
#define IDC_BUTTON_CLOSE                1019
#define IDC_EDIT16                      1019
#define IDC_IMG_INFO_EDIT_memSizeH      1019
#define IDC_EDIT17                      1020
#define IDC_IMG_INFO_EDIT_memSizeD      1020
#define IDC_EDIT18                      1022
#define IDC_TAB1                        1022
#define IDC_INDICATOR_TAB               1022
#define IDC_INSPECTOR_TAB               1022
#define IDC_IMG_INFO_EDIT_memSizeT      1022
#define IDC_EDIT19                      1023
#define IDC_EDIT20                      1024
#define IDC_EDIT21                      1025
#define IDC_IMG_INFO_EDIT_imageName     1026
#define IDC_EDIT22                      1027
#define IDC_IMG_INFO_EDIT_volSizeW      1027
#define IDC_EDIT23                      1028
#define IDC_IMG_INFO_EDIT_volSizeH      1028
#define IDC_EDIT24                      1029
#define IDC_IMG_INFO_EDIT_volSizeD      1029
#define IDC_IMG_INFO_EDIT_spacingX      1030
#define IDC_IMG_INFO_EDIT_spacingY      1031
#define IDC_IMG_INFO_EDIT_spacingZ      1032
#define IDC_SERVER_ACTIVE_userId        1034
#define IDC_LOG_LISTBOX_log             1036
#define IDC_SLICE_FILTER_chartView      1037
#define IDC_VOLUME_RENDERING_FILTER_chartViewRed 1038
#define IDC_VOLUME_RENDERING_FILTER_chartView 1038
#define IDC_VOLUME_RENDERING_FILTER_chartViewGreen 1040
#define IDC_VOLUME_RENDERING_FILTER_chartViewBlue 1043
#define IDC_VOLUME_RENDERING_FILTER_chartViewAlpha 1044
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_CLOUD                 32771
#define ID_MAIN_RIBBON_VOLUME_FILTER    32790
#define ID_MAIN_RIBBON_SLICE_FILTER     32791
#define ID_MAIN_RIBBON_BUTTON_initSliceFilter 32792
#define ID_MAIN_RIBBON_BUTTON_setSliceFilter 32796
#define ID_MAIN_RIBBON_BUTTON_setVolumeFilter 32798
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilter 32799
#define ID_MENU_SLICE_FILTER_EDIT_init  32800
#define ID_MENU_SLICE_FILTER_EDIT_initSliceFilter 32801
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_initRedFilter 32806
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_initGreenFilter 32807
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_initBlueFilter 32808
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_initAllFilter 32809
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_initAlphaFilter 32811
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_toggleTargetFilterRed 32818
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_toggleTargetFilterGreen 32819
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_toggleTargetFilterBlue 32820
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_toggleTargetFilterAlpha 32821
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_selectAllTargetFilter 32822
#define ID_MENU_VOLUME_RENDERING_FILTER_EDIT_selectNoneTargetFilter 32824
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilterGreen 32831
#define ID_MAIN_RIBBON_EDIT_slicingPointX 32833
#define ID_MAIN_RIBBON_EDIT_slicingPointY 32834
#define ID_MAIN_RIBBON_EDIT_slicingPointZ 32835
#define ID_MAIN_RIBBON_BUTTON_initSlicinigPoint 32836
#define ID_MAIN_RIBBON_EDIT_anchorAdjX_right 32837
#define ID_MAIN_RIBBON_EDIT_anchorAdjY_right 32838
#define ID_MAIN_RIBBON_BUTTON_initAnchorAdj_top 32846
#define ID_MAIN_RIBBON_BUTTON_initAnchorAdj_front 32847
#define ID_MAIN_RIBBON_BUTTON_initAnchorAdj_right 32848
#define ID_MAIN_RIBBON_EDIT_anchorAdjX_top 32849
#define ID_MAIN_RIBBON_EDIT_anchorAdjY_top 32850
#define ID_MAIN_RIBBON_EDIT_anchorAdjX_front 32851
#define ID_MAIN_RIBBON_EDIT_anchorAdjY_front 32852
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilterAll 32853
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilterRed 32854
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilterBlue 32855
#define ID_MAIN_RIBBON_BUTTON_initVolumeFilterAlpha 32856
#define ID_MAIN_RIBBON_BUTTON_analysis  32857
#define ID_MAIN_RIBBON_BUTTON_togglelLight3 32858
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight3SpecularColor 32859
#define ID_MAIN_RIBBON_EDIT_setLight3ZPos 32860
#define ID_MAIN_RIBBON_BUTTON_togglelLight1 32861
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight1AmbientColor 32862
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight1DiffuseColor 32863
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight1SpecularColor 32864
#define ID_MAIN_RIBBON_EDIT_setLight1XPos 32865
#define ID_MAIN_RIBBON_EDIT_setLight1YPos 32866
#define ID_MAIN_RIBBON_EDIT_setLight1ZPos 32867
#define ID_MAIN_RIBBON_BUTTON_togglelLight2 32868
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight2AmbientColor 32869
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight2DiffuseColor 32870
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight2SpecularColor 32871
#define ID_MAIN_RIBBON_EDIT_setLight2XPos 32872
#define ID_MAIN_RIBBON_EDIT_setLight2YPos 32873
#define ID_MAIN_RIBBON_EDIT_setLight2ZPos 32874
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight3AmbientColor 32875
#define ID_MAIN_RIBBON_COLOR_BUTTON_setLight3DiffuseColor 32876
#define ID_MAIN_RIBBON_EDIT_setLight3XPos 32877
#define ID_MAIN_RIBBON_EDIT_setLight3YPos 32878

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         32886
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
